# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://pureyb.github.io
date_format: "ordinal"
title: bo
subtitle: "橘子辉煌o"
description: "杨博的个人博客"
keywords: bo,
timezone: Asia/HangZhou
encoding: "utf-8"
side_bar_repo_limit: 5
repository: pureyb/pureyb.github.io
# 对 css 和 js 资源的 cdn 加速配置
cdn:
    jsdelivr:
        enabled: true
# 组件配置
components:
    # 分享
    share:
        enabled: false
    # 不蒜子访问统计
    busuanzi:
        enabled: true
        start_date: 2020-05-03
# 压缩页面内容
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
# 文章字数统计
word_count:
    enabled: true
# 代码高亮风格，支持的 theme 列表见 https://github.com/mzlogin/rouge-themes
highlight_theme: github

# ---------------- #
#      Author      #
# ---------------- #
author: bo.Yang
organization:
organization_url:
github_username: pureyb
location: HangZhou, China
email: bo.yang@oidbo.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /archives/
    label: 归档

#   -
#     href: /open-source/
#     label: 开源

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji



# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# https://disqus.com
gitment:
    owner: pureyb
    repo: blog-comments
    enable: false
    oauth:
        client_id: bb358de60a8ab536d52e
        client_secret: c3f07830f750d006804c2f8e6ea4a98b08afcc17
# https://github.com/gitalk/gitalk#install
gitalk:
  enable: true
  ClientID: bb358de60a8ab536d52e
  ClientSecret: c3f07830f750d006804c2f8e6ea4a98b08afcc17
  repo: blog-comments
  owner: pureyb
  IdPrefix: gitalk
  labels: gitalk
  id: location.pathname
  perPage: 10
  pagerDirection: last
  createIssueManually: true
  distractionFreeMode: false
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: true
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#      Google      #
# ---------------- #
google:
    analytics_id: UA-80669434-1
    adsense:
        footer: true
        sidebar: true
        content_header: true
        content_footer: false
